// <auto-generated />
using Clockwork.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using System;

namespace Clockwork.API.Migrations
{
    [DbContext(typeof(ClockworkContext))]
    partial class ClockworkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Clockwork.API.Core.Models.CurrentTimeQuery", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClientIp");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<DateTime>("Time");

                    b.Property<DateTime>("UTCTime");
                    b.Property<string>("DisplayName");

                    b.Property<string>("DisplayId");

                    b.HasKey("ID");

                    b.ToTable("CurrentTimeQueries");
                });

            modelBuilder.Entity("Clockwork.API.Core.Models.ServiceLogging", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<string>("Domain");

                    b.Property<string>("Message");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<int>("Type");

                    b.Property<string>("User");

                    b.Property<string>("WorkStation");

                    b.HasKey("ID");

                    b.ToTable("ServiceLoggings");
                });
#pragma warning restore 612, 618
        }
    }
}
